name: WaypointCompass
version: ${project.version}
main: me.kyleseven.waypointcompass.WaypointCompass
api-version: 1.13
authors: [kyleseven]
description: Lets players set waypoints and make their compass point toward them.